---
title: 'Appendix: Landsat Filters'
author: "B. Steele"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# read in libraries and functions
source('scripts/R_library.R')

# point to directories
datadir = '~/GitHub/ids-ne-lakes/data/'
C1_datadir <- '~/GitHub/ids-ne-lakes/data/colab-output/C1/'
C2_datadir <- '~/GitHub/ids-ne-lakes/data/colab-output/C2/'
fig_dir <- '~/GitHub/ids-ne-lakes/figures/'

```

Read in the data and filter into separate datasets.
```{r cars}

C2ST <- read.csv(file.path(C2_datadir,paste0('sunapee_paired_C2_QAQCflag_v2021-11-1.csv')), row.names = F)

C2ST_freeze <- C2ST %>% 
  filter(freeze_QAQC == 'P')

C2ST_freeze %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_maxrange <- C2ST %>% 
  filter(freeze_QAQC == 'P' & 
           spread_QAQC == 'P')

C2ST_maxrange %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_maxIQR <- C2ST %>% 
  filter(freeze_QAQC == 'P' & 
           IQR_QAQC == 'P')

C2ST_maxIQR %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_cloud <- C2ST %>% 
  filter(freeze_QAQC == 'P' & cloud_cover <40)

C2ST_cloud %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))
```



```{r pressure, echo=FALSE}
C2ST_freeze <- C2ST %>% 
  filter(freeze_QAQC == 'P')

C2ST_freeze %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_maxrange <- C2ST %>% 
  filter(freeze_QAQC == 'P' & 
           spread_QAQC == 'P')

C2ST_maxrange %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_maxIQR <- C2ST %>% 
  filter(freeze_QAQC == 'P' & 
           IQR_QAQC == 'P')

C2ST_maxIQR %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_cloud <- C2ST %>% 
  filter(freeze_QAQC == 'P' & cloud_cover <40)

C2ST_cloud %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

C2ST_kurtosis <- C2ST %>% 
  filter(surface_temp_kurtosis > 2)

C2ST_kurtosis %>% 
  group_by(LSmission) %>% 
  summarize(count = length(LSmission))

# Deming Regressions ####

# deming regression for C1
C1_deming = deming::deming(C1SC$surface_temp_median ~ C1SC$is_temp_med)
C1_deming_forresid = mcreg(x = C1SC$is_temp_med, y = C1SC$surface_temp_median, method.reg = 'Deming')
C1SC$opt_resid = MCResult.getResiduals(C1_deming_forresid)$optimized
C1SC$filter = 'none'

# deming regression for C2
C2_deming = deming::deming(C2ST$surface_temp_median ~ C2ST$is_temp_med)
C2_deming_forresid = mcreg(x = C2ST$is_temp_med, y = C2ST$surface_temp_median, method.reg = 'Deming')
C2ST$opt_resid = MCResult.getResiduals(C2_deming_forresid)$optimized
C2ST$filter = 'none'

# deming regression for C2 without freezing temps
C2_freeze_deming = deming::deming(C2ST_freeze$surface_temp_median ~ C2ST_freeze$is_temp_med)
C2_freeze_deming_forresid = mcreg(x = C2ST_freeze$is_temp_med, 
                           y = C2ST_freeze$surface_temp_median, 
                           method.reg = 'Deming')
C2ST_freeze$opt_resid = MCResult.getResiduals(C2_freeze_deming_forresid)$optimized
C2ST_freeze$filter = 'freeze'

# deming regression for C2 without freezing temps and within range
C2_maxrange_deming = deming::deming(C2ST_maxrange$surface_temp_median ~ C2ST_maxrange$is_temp_med)
C2_maxrange_deming_forresid = mcreg(x = C2ST_maxrange$is_temp_med, 
                                  y = C2ST_maxrange$surface_temp_median, 
                                  method.reg = 'Deming')
C2ST_maxrange$opt_resid = MCResult.getResiduals(C2_maxrange_deming_forresid)$optimized
C2ST_maxrange$filter = 'range'

# deming regression for C2 without freezing temps and within IQR
C2_maxIQR_deming = deming::deming(C2ST_maxIQR$surface_temp_median ~ C2ST_maxIQR$is_temp_med)
C2_maxIQR_deming_forresid = mcreg(x = C2ST_maxIQR$is_temp_med, 
                                  y = C2ST_maxIQR$surface_temp_median, 
                                  method.reg = 'Deming')
C2ST_maxIQR$opt_resid = MCResult.getResiduals(C2_maxIQR_deming_forresid)$optimized
C2ST_maxIQR$filter = 'IQR'

# deming regression for C2 without freezing temps and within IQR and data from the buoy only
C2_cloud_deming = deming::deming(C2ST_cloud$surface_temp_median ~ 
                                        C2ST_cloud$is_temp_med)
C2_cloud_deming_forresid = mcreg(x = C2ST_cloud$is_temp_med, 
                                  y = C2ST_cloud$surface_temp_median, 
                                  method.reg = 'Deming')
C2ST_cloud$opt_resid = MCResult.getResiduals(C2_cloud_deming_forresid)$optimized
C2ST_cloud$filter = 'cloud'

#deming regress for C2 with kurtosis >= 2
C2_kurtosis_deming = deming::deming(C2ST_kurtosis$surface_temp_median ~ 
                                   C2ST_kurtosis$is_temp_med)
C2_kurtosis_deming_forresid = mcreg(x = C2ST_kurtosis$is_temp_med, 
                                 y = C2ST_kurtosis$surface_temp_median, 
                                 method.reg = 'Deming')
C2ST_kurtosis$opt_resid = MCResult.getResiduals(C2_kurtosis_deming_forresid)$optimized
C2ST_kurtosis$filter = 'kurtosis'


C1_deming
cor(C1SC$surface_temp_median, C1SC$is_temp_med)

C2_deming
cor(C2ST$surface_temp_median, C2ST$is_temp_med)

C2_freeze_deming
cor(C2ST_freeze$surface_temp_median, C2ST_freeze$is_temp_med)

C2_maxrange_deming
cor(C2ST_maxrange$surface_temp_median, C2ST_maxrange$is_temp_med)

C2_maxIQR_deming
cor(C2ST_maxIQR$surface_temp_median, C2ST_maxIQR$is_temp_med)

C2_cloud_deming
cor(C2ST_cloud$surface_temp_median, C2ST_cloud$is_temp_med)

C2_kurtosis_deming
cor(C2ST_kurtosis$surface_temp_median, C2ST_kurtosis$is_temp_med)
```

```{r}
# Plot Deming regression for all filters ####
FigC_a <- ggplot(C1SC, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C1
  geom_abline(intercept = C1_deming$coefficients[1], slope = C1_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C1_deming$ci[1,1], slope = C1_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C1_deming$ci[1,2], slope = C1_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C1SC$surface_temp_median, C1SC$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C1SC$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = '',
       y = '\n',
       title = 'Collection 1',
       subtitle = 'single-channel algorithm') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_a

FigC_b <- ggplot(C2ST, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2
  geom_abline(intercept = C2_deming$coefficients[1], slope = C2_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_deming$ci[1,1], slope = C2_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_deming$ci[1,2], slope = C2_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST$surface_temp_median, C2ST$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = '',
       y = '\n',
       title = 'Collection 2',
       subtitle = '') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_b

FigC_c <- ggplot(C2ST_freeze, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2 filtered for freezing mins
  geom_abline(intercept = C2_freeze_deming$coefficients[1], slope = C2_freeze_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_freeze_deming$ci[1,1], slope = C2_freeze_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_freeze_deming$ci[1,2], slope = C2_freeze_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST_freeze$surface_temp_median, C2ST_freeze$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST_freeze$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = '',
       y = '\n',
       title = 'Collection 2',
       subtitle = 'freeze') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_c

FigC_f <- ggplot(C2ST_maxrange, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2 filtered for sub zero and maxrange
  geom_abline(intercept = C2_maxrange_deming$coefficients[1], slope = C2_maxrange_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_maxrange_deming$ci[1,1], slope = C2_maxrange_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_maxrange_deming$ci[1,2], slope = C2_maxrange_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST_maxrange$surface_temp_median, C2ST_maxrange$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST_maxrange$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = expression(bold(paste(italic('in-situ'), ' median water temp (deg C)'))),
       y = '\n',
       title = 'Collection 2',
       subtitle = 'range') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_f

FigC_d <- ggplot(C2ST_maxIQR, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2 filtered for sub zero and maxIQR
  geom_abline(intercept = C2_maxIQR_deming$coefficients[1], slope = C2_maxIQR_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_maxIQR_deming$ci[1,1], slope = C2_maxIQR_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_maxIQR_deming$ci[1,2], slope = C2_maxIQR_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST_maxIQR$surface_temp_median, C2ST_maxIQR$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST_maxIQR$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = expression(bold(paste(italic('in-situ'), ' median water temp (deg C)'))),
       y = 'median Landsat-derived\nsurface temperature (deg C)',
       title = 'Collection 2',
       subtitle = 'IQR') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_d

FigC_e <- ggplot(C2ST_cloud, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2 filtered for sub zero and cloud
  geom_abline(intercept = C2_cloud_deming$coefficients[1], slope = C2_cloud_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_cloud_deming$ci[1,1], slope = C2_cloud_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_cloud_deming$ci[1,2], slope = C2_cloud_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST_cloud$surface_temp_median, C2ST_cloud$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST_cloud$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = expression(bold(paste(italic('in-situ'), ' median water temp (deg C)'))),
       y = '\n',
       title = 'Collection 2',
       subtitle = 'cloud') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_e

FigC_g <- ggplot(C2ST_kurtosis, aes(x = is_temp_med, y = surface_temp_median)) +
  geom_abline(slope = 1, intercept = 0, color = '#006cd1', size = 0.75) +
  geom_point() +
  #add deming regression and prediction intervals for C2 filtered for sub zero and kurtosis
  geom_abline(intercept = C2_kurtosis_deming$coefficients[1], slope = C2_kurtosis_deming$coefficients[2], size = 0.75) +
  geom_abline(intercept = C2_kurtosis_deming$ci[1,1], slope = C2_kurtosis_deming$ci[2,1], linetype = 3, size = 0.75) +
  geom_abline(intercept = C2_kurtosis_deming$ci[1,2], slope = C2_kurtosis_deming$ci[2,2], linetype = 3, size = 0.75) +
  geom_text(label = paste0('r = ', round(cor(C2ST_kurtosis$surface_temp_median, C2ST_kurtosis$is_temp_med), digits = 3)),
            x = 2,
            y = 25,
            size = 4,
            hjust = 0)+
  geom_text(label = paste0('n = ', length(C2ST_kurtosis$date)),
            x = 2,
            y = 23,
            size = 4,
            hjust = 0)+
  labs(x = expression(bold(paste(italic('in-situ'), ' median water temp (deg C)'))),
       y = '\n',
       title = 'Collection 2',
       subtitle = 'kurtosis') +
  final_theme +
  coord_cartesian(xlim = c(0, 27),
                  ylim = c(0, 27))
FigC_g


FigC_plot <- plot_grid(FigC_a, FigC_b, FigC_c, FigC_d, FigC_g, FigC_e,NULL,
                   FigC_f,NULL,
                   ncol = 3,
                   labels = c('a', 'b', 'c', 'd', 'e', 'f', '', 'g', ''),
                   label_x = 0.15)

FigC_plot

ggsave(file.path(fig_dir, 'FigureC_deming_filters.jpg'), 
       dpi = 300,
       height = 12,
       width = 12,
       units = 'in')
```

```{r}
# Plot slope and intercept with 95%ci ####
slope_int_table <- NULL

slope_int_table$model = c( 'C2ST', 'C2ST_freeze', 'C2ST_maxrange', 'C2ST_kurtosis', 'C2ST_maxIQR', 'C2ST_cloud')
slope_int_table$slope = c(C2_deming$coefficients[2],
                          C2_freeze_deming$coefficients[2],
                          C2_maxrange_deming$coefficients[2],
                          C2_kurtosis_deming$coefficients[2],
                          C2_maxIQR_deming$coefficients[2],
                          C2_cloud_deming$coefficients[2])
slope_int_table$intercept = c(C2_deming$coefficients[1],
                              C2_freeze_deming$coefficients[1],
                              C2_maxrange_deming$coefficients[1],
                              C2_kurtosis_deming$coefficients[1],
                              C2_maxIQR_deming$coefficients[1],
                              C2_cloud_deming$coefficients[1])
slope_int_table$slope_se = c(C2_deming$se[2],
                             C2_freeze_deming$se[2],
                             C2_maxrange_deming$se[2],
                             C2_kurtosis_deming$se[2],
                             C2_maxIQR_deming$se[2],
                             C2_cloud_deming$se[2])
slope_int_table$int_se = c(  C2_deming$se[1],
                             C2_freeze_deming$se[1],
                             C2_maxrange_deming$se[1],
                             C2_kurtosis_deming$se[1],
                             C2_maxIQR_deming$se[1],
                             C2_cloud_deming$se[1])
slope_int_table <- as.data.frame(slope_int_table)

slope_int_table <- slope_int_table %>% 
  pivot_longer(cols = c(slope, intercept), names_to = 'var', values_to = 'value') %>% 
  mutate(se = case_when(var == 'slope' ~ slope_se,
                        var == 'intercept' ~ int_se,
                        TRUE ~ NA_real_),
         u95 = value + se,
         l95 = value - se) %>% 
  select(-slope_se, -int_se) %>% 
  mutate(model = factor(model, 
                        levels = c('C2ST', 'C2ST_freeze','C2ST_maxIQR', 'C2ST_kurtosis', 'C2ST_cloud', 'C2ST_maxrange'),
                        labels = c('Collection 2', 'Collection 2\nfreeze', 'Collection 2\nIQR', 'Collection 2\nkurtosis', 'Collection 2\ncloud','Collection 2\nrange'))) %>% 
  mutate(regression = 'Deming')

slope_fig <- slope_int_table %>% 
  filter(var == 'slope') %>% 
  ggplot(., aes(x = model, y = value)) +
  geom_point() +
  geom_pointrange(aes(ymin = l95, ymax = u95))+
  geom_abline(intercept = 1, slope = 0, color = '#454545', lty=2) +
  labs(x = NULL,
       y = 'estimated slope') +
  coord_cartesian(ylim = c(0.85, 1.15)) +
  final_theme
int_fig <- slope_int_table %>% 
  filter(var == 'intercept') %>% 
  ggplot(., aes(x = model, y = value)) +
  geom_point() +
  geom_pointrange(aes(ymin = l95, ymax = u95))+
  geom_abline(intercept = 0, slope = 0, color = '#454545', lty=2) +
  labs(x = NULL,
       y = 'estmiated intercept') +
  coord_cartesian(ylim = c(-3.2, 0)) +
  final_theme

slope_int_fig <- plot_grid(slope_fig, int_fig,
                           ncol = 1,
                           labels = c('a', 'b'))
slope_int_fig

ggsave(file.path(fig_dir, 'FigureF_slopeintercept.jpg'), 
       dpi = 300,
       height = 6,
       width = 8,
       units = 'in')

```

