---
title: "Sunapee Temp and LS LST"
author: "B. Steele"
date: \today
output: html_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(ggthemes)
library(mcr)

final_theme=theme_bw() +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        plot.title=element_text(size=16, face='bold', hjust=0.5))

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

dir = 'C:/Users/steeleb/Documents/GitHub/ids-ne-lakes/'

lst_insitu <- read_csv(paste0(dir, 'data/temp_sunapee_paired.csv'),
                       col_types = c('')) %>% 
  filter(count>0) %>% 
  mutate(date =as.Date(substrRight(`system:index`, 8), '%Y%m%d'),
         month = as.factor(format(date, '%m')),
         year = as.factor(format(date, '%Y')),
         doy = as.numeric(format(date, '%j')))

```


## Visualizations of *in-situ* temperature and Landsat LST predictions

Here, we are visualizing the LS LST predictions made by Christina Herrick, UNH, for upcoming mansucripts

#### predicted v observed
```{r}
lst_insitu_ls <- lm(lst_insitu$surface_temp_mean ~ lst_insitu$avg_temp)
summary(lst_insitu_ls)

lst_insitu_dem <-deming::deming(lst_insitu$surface_temp_mean ~ lst_insitu$avg_temp)
lst_insitu_dem

ggplot(lst_insitu, aes(x = avg_temp, y = surface_temp_mean)) +
  geom_point() +
  geom_abline(intercept = lst_insitu_dem$coefficients[1], slope = lst_insitu_dem$coefficients[2], color = 'blue') +
  geom_abline(intercept = lst_insitu_dem$ci[1,1], slope = lst_insitu_dem$ci[2,1], color = 'blue', linetype = 2) +
  geom_abline(intercept = lst_insitu_dem$ci[1,2], slope = lst_insitu_dem$ci[2,2], color = 'blue', linetype = 2) +
  geom_abline(intercept = 0, slope = 1) +
  labs(y = 'satellite-derived mean LST (deg C)', 
       x = 'in-situ mean water temp (deg C)') +
  final_theme
ggsave(paste0(dir, 'figures/predicted-observed_v02Mar2021.jpg'), height = 5, width = 5, units = 'in')
```


#### plot residuals by x
```{r}
lst_insitu_dem_forresid = mcreg(x = lst_insitu$avg_temp, y = lst_insitu$surface_temp_mean, method.reg = 'Deming')
lst_insitu$opt_resid = MCResult.getResiduals(lst_insitu_dem_forresid)$optimized

ggplot(lst_insitu, aes (y = opt_resid, x = avg_temp)) +
  geom_point() +
  labs(x = 'in-situ mean water temp (deg C)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_x_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = avg_temp, color = month)) +
  geom_point(size = 2) +
  labs(x = 'in-situ mean water temp (deg C)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme +
  scale_color_colorblind()
ggsave(paste0(dir, 'figures/optresid_x_colorbymonth_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')
```

#### residuals by cloud cover
```{r}
ggplot(lst_insitu, aes (y = opt_resid, x = cloud_cover)) +
  geom_point() +
  labs(x = 'cloud cover (percent)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_cloudcover_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = cloud_cover, color = month)) +
  geom_point(size = 2) +
  labs(x = 'cloud cover (percent)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme +
  scale_color_colorblind()
ggsave(paste0(dir, 'figures/optresid_cloudcover_colorbymonth_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

```

#### residuals by pixel count
```{r}
ggplot(lst_insitu, aes (y = opt_resid, x = pixel_count)) +
  geom_point() +
  labs(x = 'pixel count',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_pixelcount_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = pixel_count, color = month)) +
  geom_point(size = 2) +
  labs(x = 'pixel count',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme +
  scale_color_colorblind()
ggsave(paste0(dir, 'figures/optresid_pixelcount_colorbymonth_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

```

#### residuals by mean sample depth
```{r}
ggplot(lst_insitu, aes (y = opt_resid, x = avg_depth)) +
  geom_point() +
  labs(x = 'mean in-situ depth (m)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_insitudepth_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = avg_depth, color = month)) +
  geom_point(size = 2) +
  labs(x = 'mean in-situ depth (m)',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme +
  scale_color_colorblind()
ggsave(paste0(dir, 'figures/optresid_insitudepth_colorbymonth_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

```

#### residuals by month, year, doy
```{r}
ggplot(lst_insitu, aes (y = opt_resid, x = month)) +
  geom_point() +
  labs(x = 'month',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_month_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = month, color = pixel_count)) +
  geom_point(size = 2) +
  labs(x = 'month',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_month_bypixelcount_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = month, color = cloud_cover)) +
  geom_point(size = 2) +
  labs(x = 'month',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_month_bycloudcover_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = year)) +
  geom_point() +
  labs(x = 'year',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_year_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = year, color = pixel_count)) +
  geom_point(size = 2) +
  labs(x = 'year',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_year_bypixelcount_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = year, color = cloud_cover)) +
  geom_point(size = 2) +
  labs(x = 'year',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_year_bycloudcover_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = doy)) +
  geom_point() +
  labs(x = 'doy',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme
ggsave(paste0(dir, 'figures/optresid_doy_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = doy, color = pixel_count)) +
  geom_point(size = 2) +
  labs(x = 'doy',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_doy_bypixelcount_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')

ggplot(lst_insitu, aes (y = opt_resid, x = doy, color = cloud_cover)) +
  geom_point(size = 2) +
  labs(x = 'doy',
       y = 'deming optimized residuals (deg C)') +
  geom_hline(yintercept = 0, color = 'black') +
  final_theme 
ggsave(paste0(dir, 'figures/optresid_doy_bycloudcover_v02Mar2021.jpg'), height = 5, width = 8, units = 'in')


```


